<p><font size="6"><b>Python the basics: A quick recap</b></font></p>

> *DS Data manipulation, analysis and visualisation in Python*  
> *December, 2016*

> *© 2016, Joris Van den Bossche and Stijn Van Hoey  (<mailto:jorisvandenbossche@gmail.com>, <mailto:stijnvanhoey@gmail.com>). Licensed under [CC BY 4.0 Creative Commons](http://creativecommons.org/licenses/by/4.0/)*


## First steps

the obligatory...

In [1]:
print("Hello DS_course!") # python 3(!)

Hello DS_course!


python is a calculator

In [2]:
4*5

20

In [3]:
3**2

9

In [4]:
(3 + 4)/2, 3 + 4/2, 

(3.5, 5.0)

In [5]:
21//5, 21%5  # floor division, modulo

(4, 1)

Variable assignment

In [6]:
my_variable_name = 'DS_course'
my_variable_name

'DS_course'

In [7]:
name, age = 'John', 30
print('The age of {} is {:d}'.format(name, age))

The age of John is 30


More information on print format: https://pyformat.info/

## Loading functionalities

In [8]:
import os

In [9]:
os.listdir()

['04-reusing_code.ipynb',
 '.ipynb_checkpoints',
 '00-jupyter_introduction.ipynb',
 'data',
 '05-numpy.ipynb',
 'python_rehearsal.ipynb',
 '01-basic.ipynb',
 '03-functions.ipynb',
 '02-control_flow.ipynb']

Loading with defined short name (community agreement)

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Loading functions from any file/module/package:

In [12]:
%%file rehears1.py  
#this writes a file in your directory, check it(!)

"A demo module."

def print_it():
    """Dummy function to print the string it"""
    print('it')

Writing rehears1.py


In [13]:
import rehears1

In [14]:
rehears1.print_it()

it


In [15]:
%%file rehears2.py  
#this writes a file in your directory, check it(!)

"A demo module."

def print_it():
    """Dummy function to print the string it"""
    print('it')

def print_custom(my_input):
    """Dummy function to print the string that"""
    print(my_input)

Writing rehears2.py


In [16]:
from rehears2 import print_it, print_custom

In [17]:
print_custom('DS_course')

DS_course


<div class="alert alert-danger">
    <b>DON'T</b>: `from os import *`. Just don't
</div>

## Datatypes

### Numerical

**floats**

In [18]:
a_float = 5.

In [19]:
type(a_float)

float

**integers**

In [20]:
an_integer = 4

In [21]:
type(an_integer)

int

**booleans**

In [22]:
a_boolean = True
a_boolean

True

In [23]:
type(a_boolean)

bool

In [24]:
3 > 4 # results in boolean

False

### Containers

#### Strings

In [25]:
a_string = "abcde"
a_string

'abcde'

In [26]:
a_string.capitalize(), a_string.capitalize(), a_string.endswith('f') #,...

('Abcde', 'Abcde', False)

In [27]:
a_string.upper().replace('B', 'A')

'AACDE'

In [29]:
a_string + a_string

'abcdeabcde'

In [30]:
a_string * 5

'abcdeabcdeabcdeabcdeabcde'

#### Lists

In [31]:
a_list = [1, 'a', 3, 4]

In [32]:
a_list.append(8.2)
a_list

[1, 'a', 3, 4, 8.2]

In [33]:
a_list.reverse()
a_list

[8.2, 4, 3, 'a', 1]

<div class="alert alert-info">
    <b>REMEMBER</b>:  The list is updated in-place; a_list.reverse() does not return anything, it updates the list
</div>

In [34]:
a_list + ['b', 5]

[8.2, 4, 3, 'a', 1, 'b', 5]

In [35]:
[el*2 for el in a_list]  # list comprehensions...a short for-loop

[16.4, 8, 6, 'aa', 2]

In [36]:
[el for el in dir(list) if not el[0]=='_']

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

<div class="alert alert-success">
    <b>EXERCISE</b>: Rewrite the previous list comprehension by using a builtin string method to test if the element starts with an underscore
</div>

In [37]:
[el for el in dir(list) if not el.startswith('_')]

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

<div class="alert alert alert-success">
    <b>EXERCISE</b>: Given the sentence `the quick brown fox jumps over the lazy dog`, split the sentence in words and put all the word-lengths in a list. 
</div>

In [38]:
sentence = "the quick brown fox jumps over the lazy dog"

In [39]:
#split in words and get word lengths
[len(word) for word in sentence.split()]

[3, 5, 5, 3, 5, 4, 3, 4, 3]

#### Dictionaries

In [40]:
a_dict = {'a': 1, 'b': 2}

In [41]:
a_dict['c'] = 3
a_dict['a'] = 5

In [42]:
a_dict

{'a': 5, 'b': 2, 'c': 3}

In [43]:
a_dict.keys(), a_dict.values(), a_dict.items()

(dict_keys(['a', 'b', 'c']),
 dict_values([5, 2, 3]),
 dict_items([('a', 5), ('b', 2), ('c', 3)]))

In [44]:
an_empty_dic = dict() # or just {}
an_empty_dic

{}

**tuple**

In [45]:
a_tuple = (1, 2, 4)

<div class="alert alert-info">
    <b>REMEMBER</b>:  (), [], {} => depends from the datatype you want to create!
</div>

In [46]:
collect = a_list, a_dict

In [47]:
type(collect)

tuple

In [48]:
serie_of_numbers = 3, 4, 5

In [49]:
# Using tuples on the left-hand side of assignment allows you to extract fields
a, b, c = serie_of_numbers

In [50]:
print(c, b, a)

5 4 3


### Accessing container values

In [51]:
a_string[2:5]

'cde'

In [52]:
a_list[-2]

'a'

In [53]:
a_list = [0, 1, 2, 3]

In [54]:
a_list[:3]

[0, 1, 2]

In [55]:
a_list[::2]

[0, 2]

<div class="alert alert-success">
    <b>EXERCISE</b>: Reverse the `a_list` without using the built-in reverse method, but using an appropriate slicing command:
</div>

In [56]:
a_list[::-1]

[3, 2, 1, 0]

In [57]:
a_dict['a']

5

In [58]:
a_tuple[1]

2

<div class="alert alert-info">
    <b>REMEMBER</b>: 
    <ul>
        <li> [] for accessing elements
    </ul>
</div>

Assigning new values to items -> `mutable` vs `immutable`

In [66]:
a_list

[0, 1, 2, 3]

In [67]:
a_list[2] = 10 # element 2 changed -- mutable
a_list

[0, 1, 10, 3]

In [68]:
a_tuple[1] = 10 # cfr. a_string -- immutable
a_string[3] = 'q'

TypeError: 'tuple' object does not support item assignment

## Control flows

### for-loop

In [69]:
for i in [1, 2, 3, 4]:
    print(i)

1
2
3
4


In [70]:
for i in a_list: # anything that is a collection/container can be looped
    print(i)

0
1
10
3


<div class="alert alert-success">
    <b>EXERCISE</b>: Loop through the characters of the string `Hello DS` and print each character on a new line
</div>

In [71]:
for char in 'Hello DS':
    print(char)

H
e
l
l
o
 
D
S


In [72]:
for i in a_dict: # items, keys, values
    print(i)

a
b
c


In [73]:
for j, key in enumerate(a_dict.keys()):
    print(j, key)

0 a
1 b
2 c


<div class="alert alert-info">
    <b>REMEMBER</b>: When needing a iterator to count, just use `enumerate`. you mostly do not need i = 0 for... i = i +1.  
    Check [itertools](http://pymotw.com/2/itertools/) as well...
</div>

### while

In [74]:
b = 7
while b < 10:
    b+=1
    print(b)

8
9
10


### if statement

In [75]:
if 'a' in a_dict:
    print('a is in!')

a is in!


In [76]:
if 3 > 4:
    print('This is valid')

In [77]:
testvalue = False  # 0, 1, None, False, 4 > 3
if testvalue:
    print('valid')
else:
    raise Exception("Not valid!")

Exception: Not valid!

In [78]:
myvalue = 3
if isinstance(myvalue, str):
    print('this is a string')
elif isinstance(myvalue, float):
    print('this is a float')
elif isinstance(myvalue, list):
    print('this is a list')
else:
    print('no idea actually')

no idea actually


## Functions

We've been using functions the whole time...

In [79]:
len(a_list)

4

Calling a method on an object:

In [80]:
a_list.reverse()
a_list

[3, 10, 1, 0]

Defining a function:

In [81]:
def f(a, b, verbose=False):
    """custom summation function
    
    Parameters
    ----------
    a : number
        first number to sum
    b : number
        second number to sum   
    verbose: boolean
        require additional information (True) or not (False)
    
    Returns
    -------
    my_sum : number
        sum of the provided two input elements
    """
    
    if verbose:
        print('print a lot of information to the user')
        
    my_sum = a + b    
    
    return my_sum

In [82]:
f(2, 3, verbose=False)  # [3], '4'

5


<div class="alert alert-info">
    <b>REMEMBER</b>: () for calling functions
</div>

**Functions are objects** as well... (!)

In [83]:
def f1():
    print('this is function 1 speaking...')

def f2():
    print('this is function 2 speaking...')

In [84]:
def function_of_functions(inputfunction):
    return inputfunction()

In [85]:
function_of_functions(f1)

this is function 1 speaking...


**Anonymous functions (lambda)**

In [86]:
add_two = (lambda x: x + 2)

In [87]:
add_two(10)

12

## Numpy

In [88]:
import numpy as np

### Creating numpy array

In [89]:
np.array([1, 1.5, 2, 2.5])  #np.array(anylist)

array([ 1. ,  1.5,  2. ,  2.5])

In [90]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [91]:
np.linspace(5, 9, 3)

array([ 5.,  7.,  9.])

In [92]:
np.zeros((5, 2)), np.ones(5)

(array([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]), array([ 1.,  1.,  1.,  1.,  1.]))

In [93]:
np.zeros((5, 2)).shape, np.zeros((5, 2)).size

((5, 2), 10)

### Slicing

In [96]:
my_array = np.random.randint(2, 10, 10)
my_array

array([4, 6, 3, 9, 9, 7, 4, 4, 5, 3])

In [97]:
my_array[-2:]

array([5, 3])

Assign new values to items

In [98]:
my_array[0:7:2]

array([4, 3, 9, 4])

In [99]:
my_array[:2] = 10
my_array

array([10, 10,  3,  9,  9,  7,  4,  4,  5,  3])

In [100]:
my_array = my_array.reshape(5, 2)
my_array

array([[10, 10],
       [ 3,  9],
       [ 9,  7],
       [ 4,  4],
       [ 5,  3]])

In [101]:
my_array[0, :]

array([10, 10])

### Element-wise operations

In [102]:
my_array = np.random.randint(2, 10, 10)

In [103]:
my_array%3  # == 0

array([2, 0, 1, 2, 2, 2, 1, 0, 0, 0])

In [105]:
np.exp(my_array), np.sin(my_array)

(array([  148.4131591 ,   403.42879349,    54.59815003,  2980.95798704,
         2980.95798704,  2980.95798704,  1096.63315843,  8103.08392758,
           20.08553692,    20.08553692]),
 array([-0.95892427, -0.2794155 , -0.7568025 ,  0.98935825,  0.98935825,
         0.98935825,  0.6569866 ,  0.41211849,  0.14112001,  0.14112001]))

In [106]:
np.max(my_array)

9

In [107]:
np.cumsum(my_array) == my_array.cumsum()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [108]:
my_array.max(axis=0)

9

In [109]:
my_array * my_array  # element-wise

array([25, 36, 16, 64, 64, 64, 49, 81,  9,  9])

<div class="alert alert-info">
    <b>REMEMBER</b>: The operations do work on all elements of the array at the same time, you don't need a <strike>`for` loop<strike>
</div>

In [110]:
a_list = range(1000)
%timeit [i**2 for i in a_list]

1000 loops, best of 3: 397 µs per loop


In [111]:
an_array = np.arange(1000)
%timeit an_array**2

The slowest run took 35.73 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.48 µs per loop


### Boolean indexing and filtering (!)

In [112]:
row_array = np.random.randint(1, 20, 10)
row_array

array([16,  6, 17, 14, 10, 11,  2, 11, 13, 13])

Conditions can be checked (element-wise):

In [113]:
row_array > 5

array([ True,  True,  True,  True,  True,  True, False,  True,  True,  True], dtype=bool)

In [114]:
boolean_mask = row_array > 5

You can use this as a filter to select elements of an array:

In [115]:
row_array[boolean_mask]

array([16,  6, 17, 14, 10, 11, 11, 13, 13])

or, also to change the values in the array corresponding to these conditions:

In [116]:
row_array[boolean_mask] = 20
row_array

array([20, 20, 20, 20, 20, 20,  2, 20, 20, 20])

in short - making the values equal to 20 now -20:

In [117]:
row_array[row_array == 20] = -20
row_array

array([-20, -20, -20, -20, -20, -20,   2, -20, -20, -20])

This requires some practice...

In [118]:
AR = np.random.randint(0, 20, 15)
AR

array([ 3, 13,  4,  0, 11,  3,  0, 10, 13,  2, 16, 17, 13,  6, 11])

<div class="alert alert-success">
    <b>EXERCISE</b>: Count the number of values in AR that are larger than 10 (note: you can count with True = 1 and False = 0)
</div>

In [119]:
sum(AR > 10)

7

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even numbers of `AR` into zero-values.
</div>

In [120]:
AR[AR%2 == 0] = 0
AR

array([ 3, 13,  0,  0, 11,  3,  0,  0, 13,  0,  0, 17, 13,  0, 11])

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even positions of matrix AR into 30 values
</div>

In [121]:
AR[1::2] = 30
AR

array([ 3, 30,  0, 30, 11, 30,  0, 30, 13, 30,  0, 30, 13, 30, 11])

<div class="alert alert-success">
    <b>EXERCISE</b>: Select all values above the 75th percentile of the array AR2 ad take the square root of these values
</div>

In [122]:
AR2 = np.random.random(10)
AR2

array([ 0.86082658,  0.42308315,  0.98334737,  0.36392312,  0.54205933,
        0.73762625,  0.72091781,  0.09150791,  0.09216173,  0.53210831])

In [123]:
np.sqrt(AR2[AR2 > np.percentile(AR2, 75)])

array([ 0.9278074 ,  0.99163873,  0.8588517 ])

<div class="alert alert-success">
    <b>EXERCISE</b>: Convert all values -99 of the array AR3 into Nan-values (Note that Nan values can be provided in float arrays as `np.nan`)
</div>

In [124]:
AR3 = np.array([-99., 2., 3., 6., 8, -99., 7., 5., 6., -99.])

In [125]:
AR3[AR3 == -99.] = np.nan
AR3

array([ nan,   2.,   3.,   6.,   8.,  nan,   7.,   5.,   6.,  nan])

Ready for some real **Pandas!**