<p><font size="6"><b>Python the basics: A quick recap</b></font></p>

> *DS Data manipulation, analysis and visualisation in Python*  
> *December, 2017*

> *© 2016, Joris Van den Bossche and Stijn Van Hoey  (<mailto:jorisvandenbossche@gmail.com>, <mailto:stijnvanhoey@gmail.com>). Licensed under [CC BY 4.0 Creative Commons](http://creativecommons.org/licenses/by/4.0/)*


## First steps

the obligatory...

In [1]:
print("Hello DS_course!") # python 3(!)

Hello DS_course!


Python is a calculator

In [2]:
4*5

20

In [3]:
3**2

9

In [4]:
(3 + 4)/2, 3 + 4/2, 

(3.5, 5.0)

In [5]:
21//5, 21%5  # floor division, modulo

(4, 1)

Variable assignment

In [6]:
my_variable_name = 'DS_course'
my_variable_name

'DS_course'

In [7]:
name, age = 'John', 30
print('The age of {} is {:d}'.format(name, age))

The age of John is 30


More information on print format: https://pyformat.info/

## Loading functionalities

In [8]:
import os

In [9]:
os.listdir()

['00-jupyter_introduction.ipynb',
 '02-control_flow.ipynb',
 'python_rehearsal.ipynb',
 'data',
 'rehears1.py',
 '.ipynb_checkpoints',
 '__pycache__',
 '05-numpy.ipynb',
 '03-functions.ipynb',
 '01-basic.ipynb',
 '04-reusing_code.ipynb',
 'rehears2.py']

Loading with defined short name (community agreement)

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Loading functions from any file/module/package:

In [11]:
%%file rehears1.py  
#this writes a file in your directory, check it(!)

"A demo module."

def print_it():
    """Dummy function to print the string it"""
    print('it')

Overwriting rehears1.py


In [12]:
import rehears1

In [13]:
rehears1.print_it()

it


In [14]:
%%file rehears2.py  
#this writes a file in your directory, check it(!)

"A demo module."

def print_it():
    """Dummy function to print the string it"""
    print('it')

def print_custom(my_input):
    """Dummy function to print the string that"""
    print(my_input)

Overwriting rehears2.py


In [15]:
from rehears2 import print_it, print_custom

In [16]:
print_custom('DS_course')

DS_course


<div class="alert alert-danger">
    <b>DON'T</b>: `from os import *`. Just don't!
</div>

## Datatypes

### Numerical

**floats**

In [17]:
a_float = 5.

In [18]:
type(a_float)

float

**integers**

In [19]:
an_integer = 4

In [20]:
type(an_integer)

int

**booleans**

In [21]:
a_boolean = True
a_boolean

True

In [22]:
type(a_boolean)

bool

In [23]:
3 > 4 # results in boolean

False

### Containers

#### Strings

In [24]:
a_string = "abcde"
a_string

'abcde'

In [25]:
a_string.capitalize(), a_string.capitalize(), a_string.endswith('f') #,...

('Abcde', 'Abcde', False)

In [26]:
a_string.upper().replace('B', 'A')

'AACDE'

In [27]:
a_string + a_string

'abcdeabcde'

In [28]:
a_string * 5

'abcdeabcdeabcdeabcdeabcde'

#### Lists

In [29]:
a_list = [1, 'a', 3, 4]

In [30]:
a_list.append(8.2)
a_list

[1, 'a', 3, 4, 8.2]

In [31]:
a_list.reverse()
a_list

[8.2, 4, 3, 'a', 1]

<div class="alert alert-info">
    <b>REMEMBER</b>:  The list is updated in-place; a_list.reverse() does not return anything, it updates the list
</div>

In [32]:
a_list + ['b', 5]

[8.2, 4, 3, 'a', 1, 'b', 5]

In [33]:
[el*2 for el in a_list]  # list comprehensions...a short for-loop

[16.4, 8, 6, 'aa', 2]

In [34]:
[el for el in dir(list) if not el[0]=='_']

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

<div class="alert alert-success">
    <b>EXERCISE</b>: Rewrite the previous list comprehension by using a built-in string method to test if the element starts with an underscore
</div>

In [35]:
[el for el in dir(list) if not el.startswith('_')]

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

<div class="alert alert alert-success">
    <b>EXERCISE</b>: Given the sentence `the quick brown fox jumps over the lazy dog`, split the sentence in words and put all the word-lengths in a list. 
</div>

In [36]:
sentence = "the quick brown fox jumps over the lazy dog"

In [37]:
#split in words and get word lengths
[len(word) for word in sentence.split()]

[3, 5, 5, 3, 5, 4, 3, 4, 3]

#### Dictionaries

In [38]:
a_dict = {'a': 1, 'b': 2}

In [39]:
a_dict['c'] = 3
a_dict['a'] = 5

In [40]:
a_dict

{'a': 5, 'b': 2, 'c': 3}

In [41]:
a_dict.keys(), a_dict.values(), a_dict.items()

(dict_keys(['a', 'b', 'c']),
 dict_values([5, 2, 3]),
 dict_items([('a', 5), ('b', 2), ('c', 3)]))

In [42]:
an_empty_dic = dict() # or just {}
an_empty_dic

{}

**tuple**

In [43]:
a_tuple = (1, 2, 4)

<div class="alert alert-info">
    <b>REMEMBER</b>:  (), [], {} => depends from the datatype you want to create!
</div>

In [44]:
collect = a_list, a_dict

In [45]:
type(collect)

tuple

In [46]:
serie_of_numbers = 3, 4, 5

In [47]:
# Using tuples on the left-hand side of assignment allows you to extract fields
a, b, c = serie_of_numbers

In [48]:
print(c, b, a)

5 4 3


### Accessing container values

In [49]:
a_string[2:5]

'cde'

In [50]:
a_list[-2]

'a'

In [51]:
a_list = [0, 1, 2, 3]

In [52]:
a_list[:3]

[0, 1, 2]

In [53]:
a_list[::2]

[0, 2]

<div class="alert alert-success">
    <b>EXERCISE</b>: Reverse the `a_list` without using the built-in reverse method, but using an appropriate slicing command:
</div>

In [54]:
a_list[::-1]

[3, 2, 1, 0]

In [55]:
a_dict['a']

5

In [56]:
a_tuple[1]

2

<div class="alert alert-info">
    <b>REMEMBER</b>: 
    <ul>
        <li> [] for accessing elements
    </ul>
</div>

Assigning new values to items -> `mutable` vs `immutable`

In [57]:
a_list

[0, 1, 2, 3]

In [58]:
a_list[2] = 10 # element 2 changed -- mutable
a_list

[0, 1, 10, 3]

In [59]:
## TRY these yourself by un-commenting
#a_tuple[1] = 10 # cfr. a_string -- immutable
#a_string[3] = 'q'

## Control flows

### for-loop

In [60]:
for i in [1, 2, 3, 4]:
    print(i)

1
2
3
4


In [61]:
for i in a_list: # anything that is a collection/container can be looped
    print(i)

0
1
10
3


<div class="alert alert-success">
    <b>EXERCISE</b>: Loop through the characters of the string `Hello DS` and print each character on a new line
</div>

In [62]:
for char in 'Hello DS':
    print(char)

H
e
l
l
o
 
D
S


In [63]:
for i in a_dict: # items, keys, values
    print(i)

a
b
c


In [64]:
for j, key in enumerate(a_dict.keys()):
    print(j, key)

0 a
1 b
2 c


<div class="alert alert-info">
    <b>REMEMBER</b>: When needing a iterator to count, just use `enumerate`. you mostly do not need i = 0 for... i = i +1.  
    Check [itertools](http://pymotw.com/2/itertools/) as well...
</div>

### while

In [65]:
b = 7
while b < 10:
    b+=1
    print(b)

8
9
10


### if statement

In [66]:
if 'a' in a_dict:
    print('a is in!')

a is in!


In [67]:
if 3 > 4:
    print('This is valid')

In [68]:
testvalue = True  # 0, 1, None, False, 4 > 3
if testvalue:
    print('valid')
else:
    raise Exception("Not valid!")

valid


In [69]:
myvalue = 3
if isinstance(myvalue, str):
    print('this is a string')
elif isinstance(myvalue, float):
    print('this is a float')
elif isinstance(myvalue, list):
    print('this is a list')
else:
    print('no idea actually')

no idea actually


## Functions

We've been using functions the whole time...

In [70]:
len(a_list)

4

Calling a method on an object:

In [71]:
a_list.reverse()
a_list

[3, 10, 1, 0]

Defining a function:

In [72]:
def f(a, b, verbose=False):
    """custom summation function
    
    Parameters
    ----------
    a : number
        first number to sum
    b : number
        second number to sum   
    verbose: boolean
        require additional information (True) or not (False)
    
    Returns
    -------
    my_sum : number
        sum of the provided two input elements
    """
    
    if verbose:
        print('print a lot of information to the user')
        
    my_sum = a + b    
    
    return my_sum

In [73]:
f(2, 3, verbose=False)  # [3], '4'

5


<div class="alert alert-info">
    <b>REMEMBER</b>: () for calling functions
</div>

**Functions are objects** as well... (!)

In [74]:
def f1():
    print('this is function 1 speaking...')

def f2():
    print('this is function 2 speaking...')

In [75]:
def function_of_functions(inputfunction):
    return inputfunction()

In [76]:
function_of_functions(f1)

this is function 1 speaking...


**Anonymous functions (lambda)**

In [77]:
add_two = (lambda x: x + 2)

In [78]:
add_two(10)

12

## Numpy

In [79]:
import numpy as np

### Creating numpy array

In [80]:
np.array([1, 1.5, 2, 2.5])  #np.array(anylist)

array([ 1. ,  1.5,  2. ,  2.5])

In [81]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [82]:
np.linspace(5, 9, 3)

array([ 5.,  7.,  9.])

In [83]:
np.zeros((5, 2)), np.ones(5)

(array([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]), array([ 1.,  1.,  1.,  1.,  1.]))

In [84]:
np.zeros((5, 2)).shape, np.zeros((5, 2)).size

((5, 2), 10)

### Slicing

In [85]:
my_array = np.random.randint(2, 10, 10)
my_array

array([7, 9, 5, 2, 9, 5, 9, 3, 4, 4])

In [86]:
my_array[-2:]

array([4, 4])

In [87]:
my_array[0:7:2]

array([7, 5, 9, 9])

Assign new values to items

In [88]:
my_array[:2] = 10
my_array

array([10, 10,  5,  2,  9,  5,  9,  3,  4,  4])

In [89]:
my_array = my_array.reshape(5, 2)
my_array

array([[10, 10],
       [ 5,  2],
       [ 9,  5],
       [ 9,  3],
       [ 4,  4]])

In [90]:
my_array[0, :]

array([10, 10])

### Element-wise operations

In [91]:
my_array = np.random.randint(2, 10, 10)

In [92]:
my_array%3  # == 0

array([0, 2, 0, 1, 0, 1, 2, 2, 2, 2])

In [93]:
np.exp(my_array), np.sin(my_array)

(array([  4.03428793e+02,   1.48413159e+02,   4.03428793e+02,
          1.09663316e+03,   8.10308393e+03,   5.45981500e+01,
          2.98095799e+03,   7.38905610e+00,   7.38905610e+00,
          2.98095799e+03]),
 array([-0.2794155 , -0.95892427, -0.2794155 ,  0.6569866 ,  0.41211849,
        -0.7568025 ,  0.98935825,  0.90929743,  0.90929743,  0.98935825]))

In [94]:
np.max(my_array)

9

In [95]:
np.cumsum(my_array) == my_array.cumsum()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [96]:
my_array.max(axis=0)

9

In [97]:
my_array * my_array  # element-wise

array([36, 25, 36, 49, 81, 16, 64,  4,  4, 64])

<div class="alert alert-info">
    <b>REMEMBER</b>: The operations do work on all elements of the array at the same time, you don't need a <strike>`for` loop<strike>
</div>

In [98]:
a_list = range(1000)
%timeit [i**2 for i in a_list]

332 µs ± 25.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [99]:
an_array = np.arange(1000)
%timeit an_array**2

1.59 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Boolean indexing and filtering (!)

In [100]:
row_array = np.random.randint(1, 20, 10)
row_array

array([ 8,  2,  4, 18, 11,  1,  9,  3, 13,  3])

Conditions can be checked (element-wise):

In [101]:
row_array > 5

array([ True, False, False,  True,  True, False,  True, False,  True, False], dtype=bool)

In [102]:
boolean_mask = row_array > 5

You can use this as a filter to select elements of an array:

In [103]:
row_array[boolean_mask]

array([ 8, 18, 11,  9, 13])

or, also to change the values in the array corresponding to these conditions:

In [104]:
row_array[boolean_mask] = 20
row_array

array([20,  2,  4, 20, 20,  1, 20,  3, 20,  3])

in short - making the values equal to 20 now -20:

In [105]:
row_array[row_array == 20] = -20
row_array

array([-20,   2,   4, -20, -20,   1, -20,   3, -20,   3])

This requires some practice...

In [106]:
AR = np.random.randint(0, 20, 15)
AR

array([ 0,  3, 10,  8,  7,  4,  9, 17, 18, 12,  3, 11,  9,  0,  3])

<div class="alert alert-success">
    <b>EXERCISE</b>: Count the number of values in AR that are larger than 10 (note: you can count with True = 1 and False = 0)
</div>

In [107]:
sum(AR > 10)

4

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even numbers of `AR` into zero-values.
</div>

In [108]:
AR[AR%2 == 0] = 0
AR

array([ 0,  3,  0,  0,  7,  0,  9, 17,  0,  0,  3, 11,  9,  0,  3])

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even positions of matrix AR into the value 30
</div>

In [109]:
AR[1::2] = 30
AR

array([ 0, 30,  0, 30,  7, 30,  9, 30,  0, 30,  3, 30,  9, 30,  3])

<div class="alert alert-success">
    <b>EXERCISE</b>: Select all values above the 75th percentile of the following array AR2 ad take the square root of these values
</div>

In [110]:
AR2 = np.random.random(10)
AR2

array([ 0.99183267,  0.49087525,  0.28245087,  0.76397492,  0.34625795,
        0.05460881,  0.38808223,  0.37079673,  0.71920558,  0.85839014])

In [111]:
np.sqrt(AR2[AR2 > np.percentile(AR2, 75)])

array([ 0.99590796,  0.87405659,  0.92649347])

<div class="alert alert-success">
    <b>EXERCISE</b>: Convert all values -99 of the array AR3 into Nan-values (Note that Nan values can be provided in float arrays as `np.nan` and that numpy provides a specialized function to compare float values, i.e. `np.isclose()`)
</div>

In [112]:
AR3 = np.array([-99., 2., 3., 6., 8, -99., 7., 5., 6., -99.])

In [113]:
AR3[np.isclose(AR3, -99)] = np.nan
AR3

array([ nan,   2.,   3.,   6.,   8.,  nan,   7.,   5.,   6.,  nan])

Ready for some real **Pandas!**